"""add device type to page visits

Revision ID: 1ad351c4af03
Revises: 453ab77830e5
Create Date: 2026-07-24 15:38:19.584825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad351c4af03'
down_revision = '453ab77830e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=16), nullable=False))
        batch_op.drop_index(batch_op.f('ix_page_visits_visit_token'))
        batch_op.create_index(batch_op.f('ix_page_visits_visit_token'), ['visit_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_page_visits_device_type'), ['device_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_visits_device_type'))
        batch_op.drop_index(batch_op.f('ix_page_visits_visit_token'))
        batch_op.create_index(batch_op.f('ix_page_visits_visit_token'), ['visit_token'], unique=False)
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
