"""add page visit analytics

Revision ID: 453ab77830e5
Revises: 
Create Date: 2026-07-24 14:46:43.412099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453ab77830e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_key', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('visit_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_visits_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_visits_page_key'), ['page_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_visits_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_visits_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_visits_visit_token'), ['visit_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_visits_visit_token'))
        batch_op.drop_index(batch_op.f('ix_page_visits_user_id'))
        batch_op.drop_index(batch_op.f('ix_page_visits_started_at'))
        batch_op.drop_index(batch_op.f('ix_page_visits_page_key'))
        batch_op.drop_index(batch_op.f('ix_page_visits_ended_at'))

    op.drop_table('page_visits')
    # ### end Alembic commands ###
